quarkus.datasource.db-kind=mysql
#quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/registry
#quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.username=root
quarkus.datasource.password=root

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQLDialect
#quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect # -> Imposta il dialetto di Hibernate per il database H2, per generare query compatibili con H2.

# -- RIASSUNTO DELLE FUNZIONI --
# - Connessione al database (quarkus.datasource.*): Configura l'accesso al database MySQL/H2.
# - Gestione dello schema (quarkus.hibernate-orm.database.generation): Definisce come Hibernate gestisce le modifiche dello schema (aggiornamento, creazione, eliminazione).
# - Logging delle query SQL (quarkus.hibernate-orm.log.sql): Controlla se le query SQL vengono loggate.
# - Dialetto di MySQL (quarkus.hibernate-orm.dialect): Specifica il dialetto SQL di MySQL per la generazione delle query.

quarkus.swagger-ui.path=/swagger-ui

quarkus.test.continuous-testing=disabled

quarkus.console.enabled=false